# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-TreeBuilder
version:      3.09
version_from: lib/XML/TreeBuilder.pm
installdirs:  site
requires:
    HTML::Element:                 3.08
    HTML::Tagset:                  3.02
    XML::Parser:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
